### ISSUE TITLE
new WebAssembly.Instance() is always allowed, right?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/content-security-policy#14]
I just wanted to confirm, since it's not explicitly mentioned in CSP.md, that `new WebAssembly.Instance` is always allowed.  This follows since the proposal gates the creation of `WebAssembly.Module` and the `Instance` ctor necessarily takes a `Module`.

**Comment by eholk** [comment]
I think this is still kind of an open question. On the one hand, as you point out there's no reason to restrict it as long as you can't get a module any other way. On the other hand, there's no reason not to restrict it, since it's useless if you can't create a module.

**Comment by jfbastien** [comment]
Can one compile a module in one wasm-CSP-allowed and postMessage / IDB-restore it from a non-wash-CSP-allowed origin?

**Comment by lukewagner** [comment]
@eholk My motivation for asking was considering IndexedDB use cases, which is half of @jfbastien's question:
* If we *do* unconditionally allow `new Instance()`, then it follows that IndexedDB *can* be used in an origin with a strict CSP policy that disallows compile-from-buffer if a `Response` API is used (and the CSP check of the `Response` succeeds).
* Otherwise, either IndexedDB is completely disabled for strict CSP policies or we have to semantically tag `WebAssembly.Module`s with enough internal/unforgeable properties (transferred from the source `Response`, and absent when compiled-from-buffer) to do a CSP check from within `new Instance`.

@jfbastien For the other half of your question: last I saw, in the proposed spec of structured deserialize, the `Module` had to stay within the same agent cluster which means no cross-window and I *assume* means same CSP policy and so there would be no issue with `postMessage`.

Thus, I think it's a good idea to unconditionally allow `new WebAssembly.Instance()`.

**Comment by domenic** [comment]
Same agent cluster definitely allows cross window, and thus can have different CSP policies within it.

**Comment by annevk** [comment]
If those policies are in conflict you're already in trouble, unless they're cross-origin but same-site and `document.domain` isn't used, perhaps. I'm quite a big fan of the model that once you have an object, it no longer carries restrictions. (E.g., compare a blob URL and `Blob` object.) The HTML Standard effectively encourages capability-based security around message passing. It's not clear to me that adding other security mechanisms on top is a good idea.

**Comment by lukewagner** [comment]
Oops, right.  Anyhow, agreed with @annevk that, once you have a `Module`, that should be it; you are allowed to execute that module (by creating `Instance`s).

**Comment by annevk** [comment]
@eholk if you go with my rationale than no, it means that they should not be checked/marked. We definitely don't want to try to tie objects to CSP scope, that doesn't even work reliably with same-origin `<iframe>`s. At best I could see a restriction similar to `SharedyArrayBuffer`, that they have to stay inside an agent cluster. That might be beneficial if you don't want to support messaging these across process boundaries.

**Comment by titzer** [comment]
I agree with @lukewagner and @annevk that once you have a module, you should be able to instantiate it.

The postMessage() across agent clusters with different CSP policies should enforce its own access restrictions, IMO. It's an open question how to implement those access checks. E.g. I could imagine that a module compiled from a Response could also retain a robust URL; therefore postMessage() would be able to effectively enforce a CSP policy on the Module object at the boundary. However, I think probably deserves a separate issue.

As for this issue, I would suggest that we add an item to the table for 'new WebAssembly.Instance()' and mark it as allowed (like 'new WebAssembly.*Error').

**Comment by lukewagner** [comment]
Agreed, and probably split `WebAssembly.instantiate` into two rows (the `Module` overload being allowed and the `BufferSource` overload being disallowed).

**Comment by annevk** [comment]
@titzer it seems rather fragile to enforce CSP policies with `postMessage()`. It'd have to happen on the receiving side (due to MessageChannel and also BroadcastChannel I suppose), which makes success rather opaque to the sender. Anyway, happy to discuss in a new issue. (Note that a Response already holds a response which holds a URL list which is robust.)

**Comment by titzer** [comment]
I've added a table entry the instantiation variants. Closing.
