### ISSUE TITLE
WebAssembly.validate() shouldn't be blocked by CSP

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/content-security-policy#19]
While `WebAssembly.validate` takes a byte array, it doesn't produce anything executable and so shouldn't have any interaction with CSP.  Moreover, if one is going to use `WebAssembly.compileStreaming(fetch(url))` with a CSP-allowed `url`, then `WebAssembly.validate` may actually be necessary to perform feature detection beforehand.

**Comment by titzer** [comment]
Ok, I agree with the feature detection use case, so validation of some small fixed bytes should be allowed.

**Comment by titzer** [comment]
Created #20.

**Comment by lukewagner** [comment]
Thanks!
