### ISSUE TITLE
Clarify distintion between unsafe-eval and wasm-eval

### ISSUE THREAD

**Issue by pauljt** [WebAssembly/content-security-policy#2]
In the proposal, is  intent that 'unsafe-eval' ALSO enables all WebAssembly functions, as well as the proposed wasm-eval keyword  (but not vice versa)? Or is wasm-eval supposed to act independently.

**Comment by eholk** [comment]
Currently 'unsafe-eval' allows WebAssembly and all of the other things that fall under 'unsafe-eval', and we are not planning to change this behavior. The goal for 'wasm-eval' is to allow WebAssembly without allowing JS `eval()`.

Basically, 'unsafe-eval' implies 'wasm-eval', but 'wasm-eval' does not imply 'unsafe-eval'.

**Comment by eholk** [comment]
See https://github.com/w3c/webappsec-csp/pull/293 for a PR to specify `'wasm-eval'` in the CSP spec.

**Comment by titzer** [comment]
I believe this should be clear from the current text now.
