### ISSUE TITLE
Extension Permision

### ISSUE THREAD

**Issue by mariantatarau90** [WebAssembly/content-security-policy#23]
Hi Guys, 
I must give some permissions when i run webassembly in extension? because i injected wasm in a content script but give me a strange error.

> panic: JavaScript error: Permission denied to access object

Any idea?
Sorry for my bad english.

**Comment by titzer** [comment]
Since this would be a Chrome-specific issue, could you file a bug at bugs.chromium.org and attach repro instructions?
