### ISSUE TITLE
The proposed "Origin Bound Permission" potentially introduces weaknesses in nonce-based CSPs

### ISSUE THREAD

**Issue by lweichselbaum** [WebAssembly/content-security-policy#25]
Requiring host whitelist entries in script-src could render certain CSPs bypassable.
CSPs with a host whitelist in script-src can usually be bypassed with little effort [1]. For this reason CSPs that are meant to effectively mitigate XSS are either:
  - "nonce-only" i.e. they only have a nonce in script-src, but no host whitelist entry (e.g. script-src 'nonce-123';object-src 'none',base-uri 'none')
  - or also set  'strict-dynamic' and use a host whitelist only as fallback for older browsers (strict-dynamic causes the host whitelist to be ignored by CSP3 compatible browsers).

**Problem A:** The current proposal requires a host whitelist entry to e.g. allow WebAssembly.compileStreaming(Response). This will render many CSPs bypassable, if a host whitelist entry is necessary for adopting WASM. 

**Problem B:** It's not clearly defined how 'strict-dynamic' should behave in combination with 'unsafe-wasm'. I guess to not break existing behavior, the host whitelist would only be ignored for scripts, but not for WASM. This would make it even harder for developers to understand what a CSP actually does ...

**Problem C:** If any of the whitelisted domains is hosting a JSONP endpoint that reflects arbitrary bytes (similar to rossetta flash [1]), it might be possible provide attacker controlled WASM. 

**Potential solutions:**

- A,B,C) Gate WebAssembly compilation / instantiation with Trusted Trusted Types instead of CSP script-src (issue: [webappsec-trusted-types/issues/256](https://github.com/w3c/webappsec-trusted-types/issues/256))

-  A,B) Introduce a new CSP directive, e.g. wasm-src 

-  C) Require a dedicated content-type for WASM.

[1] https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45542.pdf
[2] https://blog.miki.it/2014/7/8/abusing-jsonp-with-rosetta-flash/

**Comment by hackcasual** [comment]
I'm not too familiar with CSP, but I think I at least partially understand the problems here. WebAssembly modules are by their nature sandboxes within a sandbox, only capable of executing JavaScript methods explicitly imported into the module. Therefore, I believe that makes WebAssembly loading a super set of strict-dynamic, in the sense that loading WASM requires javascript execution (no DOM injection), meaning it will only be added by something already trusted. The WASM module itself is not capable of directly adding new scripts, but instead may do so if the host script has added an import that provides that ability.

For problem C, application/wasm is required as the MIME type for the compile/instantiation streaming options: https://github.com/WebAssembly/design/blob/master/Web.md#webassemblycompilestreaming

**Comment by lweichselbaum** [comment]
I agree with you that WebAssembly has a different threat model then script tags. This is why I suggested to gate WebAssembly with Trusted Types ([webappsec-trusted-types/issues/256](https://github.com/w3c/webappsec-trusted-types/issues/256)) which deals exactly with this kind of problems or move it to it's own CSP directive.

My biggest concern is about further overloading script-src and introducing inconsistencies.
I.e. you cannot have a policy with only nonces to mitigate XSS (they must not have host whitelist entries to not become bypassable) and allow hosts for WebAssembly at the same time.

re B) Currently 'strict-dynamic' is spec'd to ignore any host whitelist entry. If we'd ignore this for wasm, it would become even harder to understand what's actually going on. Therefore, I'd personally prefer, if we'd not add more complexity to CSP/script-src 

re C) Nice! That's good know.

cc: @arturjanc @mikewest @koto

**Comment by annevk** [comment]
wasm-src or some kind of integrity metadata specified in the CSP header for Wasm resources seem like reasonable ways out.

**Comment by hackcasual** [comment]
I've been looking more into this and one thing I'm not sure about, do the attacks in *CSP Is Dead, Long Live CSP!* require adding through a DOM? If they only way of loading a WASM module is to have arbitrary script access, loading that WASM module isn't really escalating anything.

**Comment by lweichselbaum** [comment]
Most attacks on bypassing script-src host allow lists described in the paper don't require a DOM based injection (DOM-XSS) but work also for stored and reflected XSS.
However, attacks like JSONP bypasses would likely not work for WASM as application/wasm is required as MIME type.
WASM and script injections have different threat models, which I think is also an argument for separating them into two CSP directives.

**Comment by hackcasual** [comment]
Looking into the mime-type enforcement, it looks like it's forgeable by JS

```javascript

fetch('https://good.example/unsuspectingreflection?emitmalicouswasm').then(resp => {
    WebAssembly.instantiateStreaming(new Response(resp.body, {'headers': new Headers({'Content-Type': 'application/wasm'})}));
}
```

Though if we have browsers validating URLs of responses, a forged request like that wouldn't have a Request.url set. I'm not sure how I feel about mime type validation only guaranteed if you have a wasm-src <source-url> set

**Comment by lweichselbaum** [comment]
For these kinds of attacks you'd need to have javascript execution in the first place. In case of an malicious attacker, it would already be game over at this point.
If you want to protect against developers passing untrusted data/urls (by accident) to web assembly constructors, you could to look into Trusted Types.

**Comment by binji** [comment]
So if I understand, the best paths forward here are either it seems like a good path forward is either adding a `wasm-src` directive or using trusted types. But this is in addition to providing support for `wasm-unsafe-eval`, or in place of it?

**Comment by lweichselbaum** [comment]
If you want to implement sth along the lines of "Origin Bound Permission" then yes, a `wasm-src` directive or Trusted Types sound reasonable. 
`wasm-unsafe-eval` seems orthogonal to "Origin Bound Permission" and could be placed in `script-src` or `wasm-src`.
