### ISSUE TITLE
mimeTypeWasm will be added to Response

### ISSUE THREAD

**Issue by annevk** [WebAssembly/content-security-policy#3]
If this is indeed the proposal that needs to go through whatwg/fetch.

However, I object to this approach. I don't think `Response` objects should carry around format-specific knowledge. It also doesn't seem necessary as the headers of a `Response` object (unless it's a synthetic one) are immutable.

**Comment by lukewagner** [comment]
So are you saying that if the semantics first check that a `Response` came from a fetch of a URL (from #4 it sounds like that may already be "baked in" semantically) then we can trust `response.headers.get('Content-Encoding') === 'application/wasm'` for this purpose?

**Comment by annevk** [comment]
Yeah, though I wouldn't go through the JavaScript API since you cannot actually trust that.

I could be more useful I think if I understood

> In order to make WebAssembly more useful within the spirit of CSP, we should permit Response objects to carry trusted origin information.

a little better. And why you need guarantees about the MIME type.

**Comment by titzer** [comment]
As discussed in the in-meeting CG meeting at TPAC, mime types are already properly enforced for existing WASM APIs, so there is nothing more to do here.
