### ISSUE TITLE
Adding WebAssembly.compile and WebAssembly.instantiate to CSP

### ISSUE THREAD

**Issue by alpertron** [WebAssembly/content-security-policy#8]
I was reading the proposal. It appears that WebAssembly.compile and WebAssembly.instantiate will not be used with CSP because they require a byte array instead of a URL. This can be fixed by using the third syntax (hashing).

So if the hash of the byte array matches the hash specified in the HTTP header, the Web browser would accept these operations.

**Comment by mikesamuel** [comment]
> hash of the byte array matches the hash specified in the HTTP header

By "hash specified in the HTTP header", do you mean a hash that appears in a Content-Security-Policy [*hash-source*](https://www.w3.org/TR/CSP2/#hash_source)?  I ask because the relationship between HTTP headers and Content-Security-Policies is mushy.

It seems like you're proposing a spec change.  Could you expand on what you propose?

How would your proposal affect WASM pipelines that use WASM instances to decode, or instrument streaming assemblies?

**Comment by alpertron** [comment]
The Web server sends the Content Security Policy parameters in the HTTP header. So yes, something like

Content-Security-Policy: script-src 'sha256-123...456';

as specified in the document. So if the SHA-256 hash of the byte array is 123...456, the Web browser will execute WebAssembly.compile or WebAssembly.instantiate. If the hash of the byte array is different, the Web browser will show an error in the console.

As far as I know, compile and instantiate work with byte arrays that hold the Webassembly bytecode. So this is not for streaming. The operations WebAssembly.compileStreaming and WebAssembly.instantiateStreaming are already covered at https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md

**Comment by jfbastien** [comment]
It would be helpful to references existing CSP things that work in the same manner.

**Comment by alpertron** [comment]
You can see in the MDN documentation at https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Content-Security-Policy/script-src how script-src is used with JavaScript.

The example there is:

Use the following HTTP header:
`Content-Security-Policy: script-src 'sha256-076c8f1ca6979ef156b510a121b69b6265011597557ca2971db5ad5a2743545f'`

Script that can execute:
`<script>var inline = 1;</script>`

where the hash does not include the `<script>` and `</script>` tags.

In the same way, if the ArrayBuffer that holds the WebAssembly module has the specified hash, should be executed by the Web browser.

Another possibility for using securely WebAssembly from an ArrayBuffer is to use the clause 'strict-dynamic'. According to the documentation: The `'strict-dynamic'` source expression specifies that the trust explicitly given to a script present in the markup, by accompanying it with a nonce or a hash, shall be propagated to all the scripts loaded by that root script.

So just by specifying the hash of the embedding Javascript and the clause `'strict-dynamic'`, the Web browser should be able to execute the WebAssembly specified by the ArrayBuffer.

**Comment by annevk** [comment]
FWIW, I agree with @alpertron that we should do this.

cc @andypaicu

**Comment by titzer** [comment]
This seems reasonable to me as well, but the devil is in the details. Would script-src hashes intended for JS scripts apply to WASM modules, or would it make more sense to propose a separate wasm-src directive?

**Comment by titzer** [comment]
Ok, the current proposed changes contain the text:

> * WebAssembly compilation / instantiation requests that would
>   be allowed if they were script src's for non-inline JavaScript
>   will also be allowed for WebAssembly.
>   * This applies to hashes, or to origin whitelisting.

I think this captures the intent of this issue.

**Comment by alpertron** [comment]
It appears that WebAssembly.compile and WebAssembly.instantiate are missing in the third case (the one that has CSP with hash) at the end of the proposal.

**Comment by titzer** [comment]
PTAL @ #21
